stages:
  - test
  - build
  - dockerize
  - publish

.test-default:
  stage: test
  image: node:14.16.0-alpine
  cache:
    paths:
      - node_modules
  before_script:
    - yarn install
  script:
    - yarn test
  tags:
    - sl-frontend

test-mr:
  extends: .test-default
  except:
    refs:
      - tags

test-tags:
  extends: .test-default
  artifacts:
    paths:
      - node_modules
    expire_in: 1 hrs
  only:
    refs:
      - tags

build:
  stage: build
  image: node:14.16.0-alpine
  artifacts:
    paths:
      - build
    expire_in: 1 hrs
  before_script:
    - npm version $CI_COMMIT_REF_NAME
  script:
    - yarn build
  only:
    refs:
      - tags
  tags:
    - sl-frontend

build-storybook:
  stage: build
  image: node:14.16.0-alpine
  cache:
    paths:
      - node_modules
  before_script:
    - yarn install
  script:
    - yarn build-storybook
  artifacts:
    paths:
      - .build-storybook/storybook
    expire_in: 1 hrs
  only:
    refs:
      - tags
  tags:
    - sl-frontend

dockerize-storybook:
  stage: dockerize
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  dependencies:
    - build-storybook
  only:
    refs:
      - tags
  tags:
    - sl-frontend

publish-storybook:
  stage: publish
  image: registry.sima-land.ru:5043/k8s-deploy:latest
  before_script:
    - export DOMAIN_NAME=`echo $CI_ENVIRONMENT_URL | awk -F "[/:]" '{print $4}'`
    - export DEPLOY_DATE=`date +"%Y-%m-%d_%H-%M-%S"`
  script:
    - envsubst < storybook.k8s.yaml | kubectl apply -f -
  only:
    refs:
      - tags
  tags:
    - sl-frontend
  environment:
    name: moleculas-office

publish-package:
  stage: publish
  image: node:14.16.0-alpine
  before_script:
    - echo //gitlab.sima-land.ru/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN} > .npmrc
  script:
    - npm publish build
  dependencies:
    - build
  only:
    refs:
      - tags
  tags:
    - sl-frontend
