stages:
  - publish

publish-package:
  stage: publish
  image: node:10.15.3-alpine
  cache:
    paths:
      - node_modules
  before_script:
    - echo //gitlab.sima-land.ru/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN} > .npmrc
    - npm version $CI_COMMIT_REF_NAME
  script:
    - cat .npmrc
    - yarn install
    - npm publish
  tags:
    - sl-frontend
